//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodFat
    {
        public System.Guid ID { get; set; }
        public Nullable<double> BloodFat1 { get; set; }
        public Nullable<System.Guid> ClientID { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public string ExamRet { get; set; }
    }
}
