//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Body
    {
        public System.Guid ID { get; set; }
        public string WeightSum { get; set; }
        public string BMI { get; set; }
        public string FatRate { get; set; }
        public string Muscle { get; set; }
        public string Moisture { get; set; }
        public string BoneMass { get; set; }
        public string SubcutaneousFat { get; set; }
        public string BMR { get; set; }
        public string ProteinRate { get; set; }
        public string PhysicalAge { get; set; }
        public string WeightScore { get; set; }
        public Nullable<System.Guid> ClientID { get; set; }
        public string ExamRet { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
    }
}
