//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Blood { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public string ClientIdentity { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<double> Age { get; set; }
        public string Sex { get; set; }
    }
}
