//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Blood { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public string ClientIdentity { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    }
}
