//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExaminationEntities : DbContext
    {
        public ExaminationEntities()
            : base("name=ExaminationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodFat> BloodFat { get; set; }
        public virtual DbSet<BloodOxy> BloodOxy { get; set; }
        public virtual DbSet<Cardiogram> Cardiogram { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
        public virtual DbSet<UricAcid> UricAcid { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<BloodPressure> BloodPressure { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<BloodSugar> BloodSugar { get; set; }
    }
}
